### ISSUE TITLE
UnboundLocalError: local variable 'semantic_path' referenced before assignment

### ISSUE THREAD

**Issue by Tanfuchy** [sled-group/navchat#5]
when i run the code"python scripts/collect_scene_fbe.py",there is a error.

**Comment by Tanfuchy** [comment]
[2024-11-18 17:50:07 INFO] [Init] scene_ids: 4ok3usBNeis, floor_set: (-1, 1)
2024-11-18 17:50:07,079 Initializing dataset ObjectNav-v1
2024-11-18 17:50:07,091 initializing sim Sim-v0
2024-11-18 17:50:07,924 Initializing task ObjectNav-v1
[2024-11-18 17:50:07 INFO] current scene: 4ok3usBNeis
Traceback (most recent call last):
  File "scripts/collect_scene_fbe.py", line 44, in <module>
    collect_data_one_scene(scene_dic[args.scene_id][0], scene_dic[args.scene_id][1])
  File "scripts/collect_scene_fbe.py", line 22, in collect_data_one_scene
    save_new_occumap=True,
  File "/home/robot/chy_code/navchat/orion/agent_env/fbe.py", line 19, in __init__
    super().__init__(*args, **kwargs)
  File "/home/robot/chy_code/navchat/orion/agent_env/habitat/base.py", line 86, in __init__
    floor_set=floor_set,
  File "/home/robot/chy_code/navchat/orion/agent_env/habitat/base.py", line 434, in _prepare_env
    self.obj2cls_dict = self._load_semantic_annoations(kwargs["split"])
  File "/home/robot/chy_code/navchat/orion/agent_env/habitat/base.py", line 694, in _load_semantic_annoations
    with open(semantic_path, "r") as f:
UnboundLocalError: local variable 'semantic_path' referenced before assignment
